// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"time"
)

type Order struct {
	ID          int64
	Title       string
	Description string
	Link        string
	PublishedAt time.Time
	CreatedAt   time.Time
	UpdatedAt   time.Time
}
