// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: order.sql

package database

import (
	"context"
	"time"
)

const clearOrders = `-- name: ClearOrders :exec
DELETE FROM orders
`

func (q *Queries) ClearOrders(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, clearOrders)
	return err
}

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (
    title, description, link, published_at, created_at, updated_at
)
VALUES (
    ?, ?, ?, ?, ?, ?
)
RETURNING id, title, description, link, published_at, created_at, updated_at
`

type CreateOrderParams struct {
	Title       string
	Description string
	Link        string
	PublishedAt time.Time
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRowContext(ctx, createOrder,
		arg.Title,
		arg.Description,
		arg.Link,
		arg.PublishedAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Link,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
